# Generated by Django 3.1 on 2021-09-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210919_1931'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations_for_product',
            field=models.ManyToManyField(blank=True, to='store.Variation'),
        ),
    ]
